import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import NextThemeProvider from "@/components/theme-provider";
import CustomNavbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextThemeProvider>
        <body
          className={`${inter.className} text-foreground bg-background`}
          suppressHydrationWarning
        >
          <Providers>
            <CustomNavbar />
            {children}
          </Providers>
        </body>
      </NextThemeProvider>
    </html>
  );
}
